#!/usr/bin/env node

/**
 * Frontend daemon — the shared HTTP/SSE/WS server for multi-repo sparkflow.
 *
 * This process is spawned (detached) by the first `sparkflow --web` invocation
 * in any repo. Subsequent invocations find it via ~/.sparkflow/dashboard.json
 * and attach their engine daemons to it via the IPC socket.
 *
 * The process can also be started directly for testing by importing
 * `createFrontendDaemon` and calling it with custom options.
 *
 * Invocation (via web/index.ts --frontend-only):
 *   node frontend-daemon.js <ipc-socket-path> <port>
 *
 * Environment:
 *   SPARKFLOW_WEB_TOKEN — auth token (generated by the caller, 64 hex chars)
 */

import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { createConnection, type Socket } from "node:net";
import { existsSync, mkdirSync, readFileSync, realpathSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { extname, resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { WebSocketServer, type WebSocket } from "ws";
import { FrontendIpcServer, type EngineConnection } from "./frontend-ipc-server.js";
import { appendRing, RING_BUFFER_BYTES } from "./ring-buffer.js";
import type { ToolKind } from "./ipc-protocol.js";
import { pruneOldPastedImages, readBinaryBody } from "../web/paste-utils.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// frontend-daemon.js lives at <pkg>/dist/src/dashboard/. Package root is 3 up.
const PKG_ROOT = resolve(__dirname, "..", "..", "..");
const STATIC_DIR = resolve(__dirname, "..", "web", "static");
const SRC_STATIC_DIR = resolve(PKG_ROOT, "src", "web", "static");
const NODE_MODULES = resolve(PKG_ROOT, "node_modules");

// ---------------------------------------------------------------------------
// Helpers (shared with server.ts)
// ---------------------------------------------------------------------------

function getCookie(req: IncomingMessage, name: string): string | undefined {
  const header = req.headers.cookie;
  if (!header) return undefined;
  for (const part of header.split(";")) {
    const [k, ...rest] = part.trim().split("=");
    if (k === name) return rest.join("=");
  }
  return undefined;
}

function getQueryToken(url: string): string | undefined {
  const idx = url.indexOf("?");
  if (idx === -1) return undefined;
  const params = new URLSearchParams(url.slice(idx + 1));
  return params.get("token") ?? undefined;
}

function authorized(req: IncomingMessage, token: string): boolean {
  if (getCookie(req, "sf_token") === token) return true;
  if (getQueryToken(req.url ?? "") === token) return true;
  return false;
}

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".map": "application/json; charset=utf-8",
};

function sendJson(res: ServerResponse, status: number, body: unknown): void {
  const payload = Buffer.from(JSON.stringify(body), "utf-8");
  res.writeHead(status, {
    "content-type": "application/json; charset=utf-8",
    "content-length": payload.byteLength,
    "cache-control": "no-store",
  });
  res.end(payload);
}

function serveFile(res: ServerResponse, absPath: string): void {
  try {
    const stat = statSync(absPath);
    if (!stat.isFile()) {
      res.writeHead(404, { "content-type": "text/plain" });
      res.end("not found");
      return;
    }
    const body = readFileSync(absPath);
    const mime = MIME[extname(absPath).toLowerCase()] ?? "application/octet-stream";
    res.writeHead(200, {
      "content-type": mime,
      "content-length": body.byteLength,
      "cache-control": "no-cache",
    });
    res.end(body);
  } catch {
    res.writeHead(404, { "content-type": "text/plain" });
    res.end("not found");
  }
}

const APP_FILES = new Set(["index.html", "client.js", "style.css"]);
const VENDOR_FILES: Record<string, string> = {
  "xterm.css": join(NODE_MODULES, "@xterm", "xterm", "css", "xterm.css"),
  "xterm.mjs": join(NODE_MODULES, "@xterm", "xterm", "lib", "xterm.mjs"),
  "addon-fit.mjs": join(NODE_MODULES, "@xterm", "addon-fit", "lib", "addon-fit.mjs"),
};

function resolveStatic(name: string): string | null {
  const safe = name.replace(/^\/+/, "").replace(/\.\./g, "");
  if (APP_FILES.has(safe)) {
    const srcPath = join(SRC_STATIC_DIR, safe);
    if (existsSync(srcPath)) return srcPath;
    return join(STATIC_DIR, safe);
  }
  return VENDOR_FILES[safe] ?? null;
}

function readJsonBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let bytes = 0;
    req.on("data", (chunk: Buffer) => {
      bytes += chunk.byteLength;
      if (bytes > 64 * 1024) {
        reject(new Error("request body too large"));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (chunks.length === 0) { resolve({}); return; }
      try { resolve(JSON.parse(Buffer.concat(chunks).toString("utf-8"))); }
      catch (err) { reject(err instanceof Error ? err : new Error(String(err))); }
    });
    req.on("error", (err) => reject(err));
  });
}

const IMAGE_MIME_EXT: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/gif": "gif",
  "image/webp": "webp",
};

// ---------------------------------------------------------------------------
// PTY bridge proxy (connects to the primary engine's PTY bridge socket)
// ---------------------------------------------------------------------------

interface PtyBridge {
  onChatData(cb: (chatId: string, chunk: Buffer) => void): void;
  onChatList(cb: (chats: Array<{ chatId: string; kind: string; tool: ToolKind }>) => void): void;
  onChatTool(cb: (chatId: string, tool: ToolKind) => void): void;
  onChatCreated(cb: (clientReqId: string, chatId: string, tool: ToolKind) => void): void;
  onChatCreateFailed(cb: (clientReqId: string, error: string) => void): void;
  onChatClosed(cb: (chatId: string, clientReqId: string | undefined) => void): void;
  onChatCloseFailed(cb: (clientReqId: string, error: string) => void): void;
  writeTo(chatId: string, bytes: Buffer): void;
  resizeTo(chatId: string, cols: number, rows: number): void;
  setChatTool(tool: ToolKind): void;
  createChat(clientReqId: string, tool: ToolKind): void;
  closeChat(chatId: string, clientReqId: string): void;
  close(): void;
}

function connectPtyBridge(socketPath: string): Promise<PtyBridge> {
  return new Promise((resolve, reject) => {
    const sock: Socket = createConnection(socketPath);
    const chatDataCbs: Array<(chatId: string, b: Buffer) => void> = [];
    const chatListCbs: Array<(chats: Array<{ chatId: string; kind: string; tool: ToolKind }>) => void> = [];
    const chatToolCbs: Array<(chatId: string, tool: ToolKind) => void> = [];
    const chatCreatedCbs: Array<(clientReqId: string, chatId: string, tool: ToolKind) => void> = [];
    const chatCreateFailedCbs: Array<(clientReqId: string, error: string) => void> = [];
    const chatClosedCbs: Array<(chatId: string, clientReqId: string | undefined) => void> = [];
    const chatCloseFailedCbs: Array<(clientReqId: string, error: string) => void> = [];
    const pendingChatData: Array<[string, Buffer]> = [];
    const pendingChatList: Array<Array<{ chatId: string; kind: string; tool: ToolKind }>> = [];
    let buf = "";

    const bridge: PtyBridge = {
      onChatData: (cb) => {
        chatDataCbs.push(cb);
        if (pendingChatData.length > 0) {
          const queued = pendingChatData.splice(0);
          for (const [chatId, b] of queued) cb(chatId, b);
        }
      },
      onChatList: (cb) => {
        chatListCbs.push(cb);
        if (pendingChatList.length > 0) {
          const queued = pendingChatList.splice(0);
          for (const list of queued) cb(list);
        }
      },
      onChatTool: (cb) => { chatToolCbs.push(cb); },
      onChatCreated: (cb) => { chatCreatedCbs.push(cb); },
      onChatCreateFailed: (cb) => { chatCreateFailedCbs.push(cb); },
      onChatClosed: (cb) => { chatClosedCbs.push(cb); },
      onChatCloseFailed: (cb) => { chatCloseFailedCbs.push(cb); },
      writeTo: (chatId, bytes) => {
        sock.write(JSON.stringify({ type: "pty_write", chatId, bytes: bytes.toString("base64") }) + "\n");
      },
      resizeTo: (chatId, cols, rows) => {
        sock.write(JSON.stringify({ type: "pty_resize", chatId, cols, rows }) + "\n");
      },
      setChatTool: (tool) => {
        sock.write(JSON.stringify({ type: "set_chat_tool", tool }) + "\n");
      },
      createChat: (clientReqId, tool) => {
        sock.write(JSON.stringify({ type: "chat_create", clientReqId, tool }) + "\n");
      },
      closeChat: (chatId, clientReqId) => {
        sock.write(JSON.stringify({ type: "chat_close", chatId, clientReqId }) + "\n");
      },
      close: () => { try { sock.destroy(); } catch { /* ignore */ } },
    };

    sock.setEncoding("utf-8");
    sock.on("connect", () => resolve(bridge));
    sock.on("error", (err) => reject(err));
    sock.on("close", () => { /* bridge gone */ });
    sock.on("data", (chunk) => {
      buf += chunk as unknown as string;
      let nl: number;
      while ((nl = buf.indexOf("\n")) !== -1) {
        const line = buf.slice(0, nl);
        buf = buf.slice(nl + 1);
        if (!line) continue;
        try {
          const msg = JSON.parse(line) as {
            type?: string; chatId?: string; bytes?: string; tool?: string;
            chats?: Array<{ chatId: string; kind: string; tool: ToolKind }>;
            clientReqId?: string; error?: string;
          };
          if (msg.type === "chat_list" && Array.isArray(msg.chats)) {
            if (chatListCbs.length === 0) pendingChatList.push(msg.chats);
            else for (const cb of chatListCbs) cb(msg.chats);
          } else if ((msg.type === "snapshot" || msg.type === "pty_data") && typeof msg.chatId === "string" && typeof msg.bytes === "string") {
            const b = Buffer.from(msg.bytes, "base64");
            if (chatDataCbs.length === 0) pendingChatData.push([msg.chatId, b]);
            else for (const cb of chatDataCbs) cb(msg.chatId, b);
          } else if (msg.type === "chat_tool" && typeof msg.chatId === "string" && (msg.tool === "claude" || msg.tool === "gemini")) {
            for (const cb of chatToolCbs) cb(msg.chatId, msg.tool);
          } else if (msg.type === "chat_created" && typeof msg.clientReqId === "string" && typeof msg.chatId === "string" && (msg.tool === "claude" || msg.tool === "gemini")) {
            for (const cb of chatCreatedCbs) cb(msg.clientReqId, msg.chatId, msg.tool);
          } else if (msg.type === "chat_create_failed" && typeof msg.clientReqId === "string" && typeof msg.error === "string") {
            for (const cb of chatCreateFailedCbs) cb(msg.clientReqId, msg.error);
          } else if (msg.type === "chat_closed" && typeof msg.chatId === "string") {
            const clientReqId = typeof msg.clientReqId === "string" ? msg.clientReqId : undefined;
            for (const cb of chatClosedCbs) cb(msg.chatId, clientReqId);
          } else if (msg.type === "chat_close_failed" && typeof msg.clientReqId === "string" && typeof msg.error === "string") {
            for (const cb of chatCloseFailedCbs) cb(msg.clientReqId, msg.error);
          }
        } catch { /* ignore */ }
      }
    });
  });
}

// ---------------------------------------------------------------------------
// Main HTTP server factory (exported for testing)
// ---------------------------------------------------------------------------

export interface FrontendDaemonOptions {
  ipcSocketPath: string;
  port: number;
  token: string;
}

export interface FrontendDaemonHandle {
  port: number;
  ipcSocketPath: string;
  registry: FrontendIpcServer;
  close(): Promise<void>;
}

export async function createFrontendDaemon(opts: FrontendDaemonOptions): Promise<FrontendDaemonHandle> {
  const { ipcSocketPath, token } = opts;

  // Start the IPC server (engine registry)
  const registry = new FrontendIpcServer(ipcSocketPath);
  await registry.listen();

  // Per-repo PTY bridge state. Each attached engine that exposes a bridge
  // gets its own entry with a pool of per-chat states.
  interface ChatEntry {
    ring: Buffer;
    tool: ToolKind;
    kind: "main" | "sidechat";
    clients: Set<WebSocket>;
  }
  interface PendingCreate {
    resolve: (chatId: string, tool: ToolKind) => void;
    reject: (error: string) => void;
  }
  interface PendingClose {
    resolve: () => void;
    reject: (error: string) => void;
  }
  interface RepoBridgeEntry {
    bridge: PtyBridge;
    chats: Map<string, ChatEntry>;
    pendingCreates: Map<string, PendingCreate>;
    pendingCloses: Map<string, PendingClose>;
  }
  const bridges = new Map<string, RepoBridgeEntry>();
  // WebSocket clients are tracked in per-chat Sets inside RepoBridgeEntry.chats.
  // wsToRepo/wsToChat let the upgrade handler route new connections.
  const wsToRepo = new WeakMap<WebSocket, string>();
  const wsToChat = new WeakMap<WebSocket, string>();

  function onEngineAttached(conn: EngineConnection): void {
    if (conn.repoPath) pruneOldPastedImages(conn.repoPath);
    if (!conn.ptyBridgePath || bridges.has(conn.repoId)) return;
    connectPtyBridge(conn.ptyBridgePath).then((bridge) => {
      const chatMap = new Map<string, ChatEntry>();
      const pendingCreates = new Map<string, PendingCreate>();
      const pendingCloses = new Map<string, PendingClose>();
      const entry: RepoBridgeEntry = { bridge, chats: chatMap, pendingCreates, pendingCloses };
      bridges.set(conn.repoId, entry);

      bridge.onChatList((chatList) => {
        // Sync per-chat state with the engine's authoritative list.
        const newIds = new Set(chatList.map(c => c.chatId));
        for (const cId of chatMap.keys()) {
          if (!newIds.has(cId)) chatMap.delete(cId);
        }
        for (const { chatId, kind, tool } of chatList) {
          if (!chatMap.has(chatId)) {
            chatMap.set(chatId, { ring: Buffer.alloc(0), tool, kind: kind as "main" | "sidechat", clients: new Set() });
          }
        }
        const mainChat = chatList.find(c => c.chatId === "main");
        if (mainChat) registry.updateChatTool(conn.repoId, mainChat.tool as ToolKind);
      });

      bridge.onChatData((chatId, chunk) => {
        const chat = chatMap.get(chatId);
        if (!chat) return;
        chat.ring = appendRing(chat.ring, chunk, RING_BUFFER_BYTES);
        const payload = JSON.stringify({ type: "data", bytes: chunk.toString("base64") });
        for (const ws of chat.clients) {
          if (ws.readyState === ws.OPEN) ws.send(payload);
        }
      });

      bridge.onChatTool((chatId, tool) => {
        const chat = chatMap.get(chatId);
        if (chat) {
          // On tool switch the engine clears its ring; mirror that here.
          chat.ring = Buffer.alloc(0);
          chat.tool = tool;
        }
        if (chatId === "main") {
          registry.updateChatTool(conn.repoId, tool);
          const mainChat = chatMap.get("main");
          if (mainChat) {
            const payload = JSON.stringify({ type: "chat_tool", tool });
            for (const ws of mainChat.clients) {
              if (ws.readyState === ws.OPEN) ws.send(payload);
            }
          }
        }
      });

      bridge.onChatCreated((clientReqId, chatId, tool) => {
        chatMap.set(chatId, { ring: Buffer.alloc(0), tool, kind: "sidechat", clients: new Set() });
        const pending = pendingCreates.get(clientReqId);
        if (pending) {
          pendingCreates.delete(clientReqId);
          pending.resolve(chatId, tool);
        }
      });

      bridge.onChatCreateFailed((clientReqId, error) => {
        const pending = pendingCreates.get(clientReqId);
        if (pending) {
          pendingCreates.delete(clientReqId);
          pending.reject(error);
        }
      });

      bridge.onChatClosed((chatId, clientReqId) => {
        const chat = chatMap.get(chatId);
        if (chat) {
          const payload = JSON.stringify({ type: "chat_ended" });
          for (const ws of chat.clients) {
            if (ws.readyState === ws.OPEN) {
              try { ws.send(payload); } catch { /* ignore */ }
              try { ws.close(); } catch { /* ignore */ }
            }
          }
          chatMap.delete(chatId);
        }
        if (clientReqId) {
          const pending = pendingCloses.get(clientReqId);
          if (pending) {
            pendingCloses.delete(clientReqId);
            pending.resolve();
          }
        }
      });

      bridge.onChatCloseFailed((clientReqId, error) => {
        const pending = pendingCloses.get(clientReqId);
        if (pending) {
          pendingCloses.delete(clientReqId);
          pending.reject(error);
        }
      });

    }).catch(() => { /* PTY bridge unavailable — engine without chat */ });
  }

  registry.on("engineAttached", onEngineAttached);
  registry.on("engineDetached", (repoId: string) => {
    const entry = bridges.get(repoId);
    if (!entry) return;
    try { entry.bridge.close(); } catch { /* ignore */ }
    bridges.delete(repoId);
  });

  // HTTP server
  const server = createServer((req, res) => {
    const url = req.url ?? "/";
    const pathname = url.split("?")[0];

    const cookieOk = getCookie(req, "sf_token") === token;
    const queryOk = getQueryToken(url) === token;
    if (!cookieOk && !queryOk) {
      res.writeHead(401, { "content-type": "text/plain" });
      res.end("unauthorized");
      return;
    }
    if (!cookieOk && queryOk && pathname === "/") {
      res.writeHead(302, {
        "set-cookie": `sf_token=${token}; Path=/; HttpOnly; SameSite=Strict`,
        location: "/",
      });
      res.end();
      return;
    }

    // Static files
    if (pathname === "/" || pathname === "/index.html") {
      const file = resolveStatic("index.html");
      if (file) return serveFile(res, file);
    }
    if (pathname.startsWith("/static/")) {
      const file = resolveStatic(pathname.slice("/static/".length));
      if (file) return serveFile(res, file);
      res.writeHead(404, { "content-type": "text/plain" });
      res.end("not found");
      return;
    }

    // SSE: fan out all engines' jobs
    if (pathname === "/events") {
      res.writeHead(200, {
        "content-type": "text/event-stream",
        "cache-control": "no-cache",
        connection: "keep-alive",
      });
      const send = () => {
        try {
          const jobs = registry.getAllJobs();
          const repos = registry.getRepos();
          res.write(`data: ${JSON.stringify({ jobs, repos })}\n\n`);
        } catch { /* client gone */ }
      };
      send();
      const unsubscribe = registry.onUpdate(send);
      const heartbeat = setInterval(() => {
        try { res.write(": ping\n\n"); } catch { /* ignore */ }
      }, 15_000);
      req.on("close", () => {
        clearInterval(heartbeat);
        unsubscribe();
      });
      return;
    }

    // GET /repos — list attached repos
    if (pathname === "/repos" && req.method === "GET") {
      return sendJson(res, 200, { repos: registry.getRepos() });
    }

    // Per-repo job routes: /repos/:repoId/jobs/:jobId/action
    const repoJobMatch = pathname.match(
      /^\/repos\/([A-Za-z0-9_-]+)\/jobs\/([A-Za-z0-9_-]+)\/([a-z]+)$/,
    );
    if (repoJobMatch) {
      const [, repoId, jobId, action] = repoJobMatch;
      const engine = registry.getEngine(repoId);

      if (!engine) {
        return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });
      }

      if (action === "log" && req.method === "GET") {
        const params = new URLSearchParams(url.includes("?") ? url.slice(url.indexOf("?") + 1) : "");
        const since = parseInt(params.get("since") ?? "0", 10);
        registry
          .sendCommand(repoId, { type: "getJobDetail", jobId, id: randomBytes(8).toString("hex") })
          .then((r) => {
            if (!r || "error" in r) return sendJson(res, 404, { error: `Job not found: ${jobId}` });
            const output = (r.output as string[]) ?? [];
            const length = output.length;
            const safeFrom = Number.isFinite(since) && since >= 0 && since <= length ? since : 0;
            const lines = output.slice(safeFrom);
            const info = r.info as { state?: string } | undefined;
            sendJson(res, 200, { lines, length, state: info?.state ?? "unknown" });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }

      if (action === "kill" && req.method === "POST") {
        registry
          .sendCommand(repoId, { type: "killJob", jobId, id: randomBytes(8).toString("hex") })
          .then((r) => {
            if (!r || "error" in r) return sendJson(res, 400, { error: (r as { error?: string } | null)?.error ?? "kill failed" });
            sendJson(res, 200, { ok: true });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }

      if (action === "restart" && req.method === "POST") {
        registry
          .sendCommand(repoId, { type: "restartJob", jobId, id: randomBytes(8).toString("hex") })
          .then((r) => {
            if (!r || "error" in r) return sendJson(res, 400, { error: (r as { error?: string } | null)?.error ?? "restart failed" });
            const payload = r as { newJobId?: string; ok?: boolean };
            sendJson(res, 200, { ok: true, newJobId: payload.newJobId });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }

      if (action === "remove" && req.method === "POST") {
        registry
          .sendCommand(repoId, { type: "removeJob", jobId, id: randomBytes(8).toString("hex") })
          .then((r) => {
            if (!r || "error" in r) return sendJson(res, 400, { error: (r as { error?: string } | null)?.error ?? "remove failed" });
            sendJson(res, 200, { ok: true });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }

      if (action === "nudge" && req.method === "POST") {
        readJsonBody(req)
          .then((body): Promise<Record<string, unknown> | null> | null => {
            const { stepId, message } = body as { stepId?: unknown; message?: unknown };
            if (typeof message !== "string" || !message.trim()) {
              sendJson(res, 400, { error: "message is required" });
              return null;
            }
            if (message.length > 32 * 1024) {
              sendJson(res, 400, { error: "message too large (max 32KB)" });
              return null;
            }
            if (typeof stepId !== "string" || !stepId) {
              sendJson(res, 400, { error: "stepId is required" });
              return null;
            }
            return registry.sendCommand(repoId, {
              type: "nudgeJob",
              id: randomBytes(8).toString("hex"),
              jobId,
              stepId,
              message,
            });
          })
          .then((r) => {
            if (!r) return;
            if (typeof r === "object" && "error" in r) sendJson(res, 400, { error: (r as { error?: string }).error });
            else sendJson(res, 200, { ok: true });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }

      if (action === "recovery" && req.method === "POST") {
        readJsonBody(req)
          .then((body): Promise<Record<string, unknown> | null> | null => {
            const { action: recoveryAction, message } = body as { action?: string; message?: string };
            if (!recoveryAction || !["retry", "skip", "abort"].includes(recoveryAction)) {
              sendJson(res, 400, { error: "invalid action" });
              return null;
            }
            return registry.sendCommand(repoId, {
              type: "answerRecovery",
              id: randomBytes(8).toString("hex"),
              jobId,
              action: recoveryAction as "retry" | "skip" | "abort",
              message,
            });
          })
          .then((r) => {
            if (!r) return;
            if (typeof r === "object" && "error" in r) sendJson(res, 400, { error: (r as { error?: string }).error });
            else sendJson(res, 200, { ok: true });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }
    }

    // GET /repos/:repoId/chats — list all chats (main + side-chats)
    const chatsGetMatch = pathname.match(/^\/repos\/([A-Za-z0-9_-]+)\/chats$/);
    if (chatsGetMatch && req.method === "GET") {
      const [, repoId] = chatsGetMatch;
      const entry = bridges.get(repoId);
      if (!entry) return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });
      const list = [...entry.chats.entries()].map(([chatId, c]) => ({ chatId, kind: c.kind, tool: c.tool }));
      return sendJson(res, 200, list);
    }

    // POST /repos/:repoId/chats — create a new side-chat
    if (chatsGetMatch && req.method === "POST") {
      const [, repoId] = chatsGetMatch;
      const entry = bridges.get(repoId);
      if (!entry) return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });
      readJsonBody(req).then((body) => {
        const { tool = "claude" } = body as { tool?: unknown };
        if (tool !== "claude" && tool !== "gemini") {
          return sendJson(res, 400, { error: "tool must be 'claude' or 'gemini'" });
        }
        const clientReqId = randomBytes(8).toString("hex");
        const timeout = setTimeout(() => {
          entry.pendingCreates.delete(clientReqId);
          sendJson(res, 503, { error: "supervisor timeout" });
        }, 10_000);
        entry.pendingCreates.set(clientReqId, {
          resolve: (chatId, chatTool) => {
            clearTimeout(timeout);
            sendJson(res, 200, { chatId, kind: "sidechat", tool: chatTool });
          },
          reject: (error) => {
            clearTimeout(timeout);
            sendJson(res, error.includes("limit") ? 429 : 400, { error });
          },
        });
        entry.bridge.createChat(clientReqId, tool as ToolKind);
      }).catch((err: unknown) => {
        sendJson(res, 400, { error: err instanceof Error ? err.message : String(err) });
      });
      return;
    }

    // DELETE /repos/:repoId/chats/:chatId — close a side-chat
    const chatDeleteMatch = pathname.match(/^\/repos\/([A-Za-z0-9_-]+)\/chats\/([^/]+)$/);
    if (chatDeleteMatch && req.method === "DELETE") {
      const [, repoId, chatId] = chatDeleteMatch;
      if (chatId === "main") return sendJson(res, 400, { error: "cannot close main chat" });
      const entry = bridges.get(repoId);
      if (!entry) return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });
      if (!entry.chats.has(chatId)) return sendJson(res, 404, { error: "chat not found" });
      const clientReqId = randomBytes(8).toString("hex");
      const timeout = setTimeout(() => {
        entry.pendingCloses.delete(clientReqId);
        sendJson(res, 503, { error: "supervisor timeout" });
      }, 10_000);
      entry.pendingCloses.set(clientReqId, {
        resolve: () => { clearTimeout(timeout); sendJson(res, 200, { ok: true }); },
        reject: (error) => { clearTimeout(timeout); sendJson(res, 400, { error }); },
      });
      entry.bridge.closeChat(chatId, clientReqId);
      return;
    }

    // Switch the jobs tool for a specific repo's engine.
    const jobToolMatch = pathname.match(/^\/repos\/([A-Za-z0-9_-]+)\/job-tool$/);
    if (jobToolMatch && req.method === "POST") {
      const [, repoId] = jobToolMatch;
      const engine = registry.getEngine(repoId);
      if (!engine) return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });

      readJsonBody(req)
        .then((body): Promise<Record<string, unknown> | null> | null => {
          const { tool } = body as { tool?: string };
          if (tool !== "claude" && tool !== "gemini" && tool !== "codex") {
            sendJson(res, 400, { error: "tool must be 'claude', 'gemini', or 'codex'" });
            return null;
          }
          return registry.sendCommand(repoId, {
            type: "setJobTool",
            id: randomBytes(8).toString("hex"),
            tool,
          });
        })
        .then((r) => {
          if (!r) return;
          if (typeof r === "object" && "error" in r) {
            sendJson(res, 400, { error: (r as { error?: string }).error });
          } else {
            const tool = (r as { jobTool?: string }).jobTool;
            if (tool === "claude" || tool === "gemini" || tool === "codex") {
              registry.updateJobTool(repoId, tool);
            }
            sendJson(res, 200, { ok: true });
          }
        })
        .catch(() => sendJson(res, 500, { error: "engine request failed" }));
      return;
    }

    // POST /repos/:repoId/paste-image — save a pasted image to disk, return relpath
    const pasteImageMatch = pathname.match(/^\/repos\/([A-Za-z0-9_-]+)\/paste-image$/);
    if (pasteImageMatch && req.method === "POST") {
      const [, repoId] = pasteImageMatch;
      const engine = registry.getEngine(repoId);
      if (!engine) return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });
      const ct = (req.headers["content-type"] ?? "").split(";")[0].trim().toLowerCase();
      const ext = IMAGE_MIME_EXT[ct];
      if (!ext) return sendJson(res, 415, { error: `unsupported image type: ${ct}` });
      readBinaryBody(req, 10 * 1024 * 1024).then((buf) => {
        const ts = new Date().toISOString().replace(/[:.]/g, "-");
        const rand = randomBytes(4).toString("hex");
        const filename = `${ts}-${rand}.${ext}`;
        const pastedDir = join(engine.repoPath, ".sparkflow", "pasted");
        mkdirSync(pastedDir, { recursive: true });
        writeFileSync(join(pastedDir, filename), buf);
        sendJson(res, 200, { relpath: `.sparkflow/pasted/${filename}`, bytes: buf.byteLength });
      }).catch((err: unknown) => {
        const msg = err instanceof Error ? err.message : String(err);
        if (msg === "request body too large") sendJson(res, 413, { error: "image too large (max 10 MiB)" });
        else sendJson(res, 500, { error: msg });
      });
      return;
    }

    // GET /repos/:repoId/pasted/:filename — serve a pasted image by filename
    const getPastedMatch = pathname.match(/^\/repos\/([A-Za-z0-9_-]+)\/pasted\/([^/]+)$/);
    if (getPastedMatch && req.method === "GET") {
      const [, repoId, filename] = getPastedMatch;
      const engine = registry.getEngine(repoId);
      if (!engine) return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });
      if (!/^[A-Za-z0-9_.-]+\.(png|jpg|jpeg|gif|webp)$/.test(filename)) {
        return sendJson(res, 400, { error: "invalid filename" });
      }
      const EXT_MIME: Record<string, string> = {
        png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg",
        gif: "image/gif", webp: "image/webp",
      };
      const ext = filename.slice(filename.lastIndexOf(".") + 1).toLowerCase();
      const contentType = EXT_MIME[ext] ?? "application/octet-stream";
      const pastedDir = join(engine.repoPath, ".sparkflow", "pasted");
      const filePath = join(pastedDir, filename);
      try {
        const resolved = realpathSync(filePath);
        const dirResolved = realpathSync(pastedDir);
        if (!resolved.startsWith(dirResolved + "/") && resolved !== dirResolved) {
          return sendJson(res, 400, { error: "invalid path" });
        }
      } catch {
        return sendJson(res, 404, { error: "not found" });
      }
      try {
        const buf = readFileSync(filePath);
        res.writeHead(200, {
          "content-type": contentType,
          "content-length": String(buf.byteLength),
          "cache-control": "private, max-age=86400",
        });
        res.end(buf);
      } catch {
        sendJson(res, 404, { error: "not found" });
      }
      return;
    }

    // Workflow start for a specific repo
    const startWorkflowMatch = pathname.match(/^\/repos\/([A-Za-z0-9_-]+)\/start$/);
    if (startWorkflowMatch && req.method === "POST") {
      const [, repoId] = startWorkflowMatch;
      const engine = registry.getEngine(repoId);
      if (!engine) return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });

      readJsonBody(req)
        .then((body): Promise<Record<string, unknown> | null> | null => {
          const { workflowPath, cwd, plan, planText, slug, description } =
            body as {
              workflowPath?: string;
              cwd?: string;
              plan?: string;
              planText?: string;
              slug?: string;
              description?: string;
            };
          if (!workflowPath) {
            sendJson(res, 400, { error: "workflowPath is required" });
            return null;
          }
          return registry.sendCommand(repoId, {
            type: "startWorkflow",
            id: randomBytes(8).toString("hex"),
            workflowPath,
            cwd,
            plan,
            planText,
            slug,
            description,
          });
        })
        .then((r) => {
          if (!r) return;
          if (typeof r === "object" && "error" in r) sendJson(res, 400, { error: (r as { error?: string }).error });
          else sendJson(res, 200, r);
        })
        .catch(() => sendJson(res, 500, { error: "engine request failed" }));
      return;
    }

    res.writeHead(404, { "content-type": "text/plain" });
    res.end("not found");
  });

  const wss = new WebSocketServer({ noServer: true });

  function pickRepoIdFromUrl(url: string): string | null {
    const idx = url.indexOf("?");
    if (idx === -1) return null;
    const params = new URLSearchParams(url.slice(idx + 1));
    const requested = params.get("repoId");
    if (requested && bridges.has(requested)) return requested;
    // Fall back to the first attached engine with a bridge.
    for (const rid of bridges.keys()) return rid;
    return null;
  }

  server.on("upgrade", (req, socket, head) => {
    const url = req.url ?? "";
    if (url.split("?")[0] !== "/chat" || !authorized(req, token)) {
      (socket as Socket).write("HTTP/1.1 401 Unauthorized\r\n\r\n");
      (socket as Socket).destroy();
      return;
    }
    const repoId = pickRepoIdFromUrl(url);
    if (!repoId) {
      (socket as Socket).write("HTTP/1.1 503 Service Unavailable\r\n\r\n");
      (socket as Socket).destroy();
      return;
    }
    const params = new URLSearchParams(url.includes("?") ? url.slice(url.indexOf("?") + 1) : "");
    const chatId = params.get("chatId") ?? "main";
    wss.handleUpgrade(req, socket as Socket, head, (ws) => {
      wsToRepo.set(ws, repoId);
      wsToChat.set(ws, chatId);
      wss.emit("connection", ws, req);
    });
  });

  wss.on("connection", (ws: WebSocket) => {
    const repoId = wsToRepo.get(ws);
    const chatId = wsToChat.get(ws) ?? "main";
    if (!repoId) {
      try { ws.close(1011, "no repo"); } catch { /* ignore */ }
      return;
    }
    const entry = bridges.get(repoId);
    if (!entry) {
      try { ws.close(1011, "no bridge"); } catch { /* ignore */ }
      return;
    }
    const chat = entry.chats.get(chatId);
    if (!chat) {
      try { ws.close(1008, "unknown chatId"); } catch { /* ignore */ }
      return;
    }
    chat.clients.add(ws);
    if (chat.ring.length > 0) {
      ws.send(JSON.stringify({ type: "data", bytes: chat.ring.toString("base64") }));
    }
    if (chatId === "main") {
      const tool = registry.getEngine(repoId)?.chatTool;
      if (tool) ws.send(JSON.stringify({ type: "chat_tool", tool }));
    }

    ws.on("message", (raw) => {
      let parsed: unknown;
      try { parsed = JSON.parse(raw.toString("utf-8")); } catch { return; }
      const msg = parsed as { type?: string; bytes?: string; cols?: number; rows?: number; tool?: string };
      const current = bridges.get(repoId);
      if (!current) return;
      if (msg.type === "data" && typeof msg.bytes === "string") {
        try { current.bridge.writeTo(chatId, Buffer.from(msg.bytes, "base64")); } catch { /* ignore */ }
      } else if (msg.type === "resize" && Number.isFinite(msg.cols) && Number.isFinite(msg.rows)) {
        try { current.bridge.resizeTo(chatId, Math.max(1, msg.cols!), Math.max(1, msg.rows!)); } catch { /* ignore */ }
      } else if (msg.type === "set_chat_tool" && (msg.tool === "claude" || msg.tool === "gemini") && chatId === "main") {
        try { current.bridge.setChatTool(msg.tool); } catch { /* ignore */ }
      }
    });

    ws.on("close", () => {
      const e = bridges.get(repoId);
      e?.chats.get(chatId)?.clients.delete(ws);
    });
  });

  await new Promise<void>((resolve) => server.listen(opts.port, "127.0.0.1", () => resolve()));

  const address = server.address();
  const boundPort = typeof address === "object" && address ? address.port : opts.port;

  return {
    port: boundPort,
    ipcSocketPath,
    registry,
    close: async () => {
      await registry.close();
      await new Promise<void>((resolve) => server.close(() => resolve()));
    },
  };
}

// ---------------------------------------------------------------------------
// Process entry point
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  if (argv.length < 2) {
    console.error("Usage: frontend-daemon <ipc-socket-path> <port>");
    process.exit(1);
  }
  const [ipcSocketPath, portStr] = argv;
  const port = parseInt(portStr, 10);
  if (Number.isNaN(port) || port < 0) {
    console.error(`Invalid port: ${portStr}`);
    process.exit(1);
  }

  const token = process.env.SPARKFLOW_WEB_TOKEN;
  if (!token || !/^[0-9a-f]{64}$/.test(token)) {
    console.error("[sparkflow frontend] missing or malformed SPARKFLOW_WEB_TOKEN");
    process.exit(1);
  }

  const handle = await createFrontendDaemon({ ipcSocketPath, port, token });

  process.stderr.write(
    `\n[sparkflow web] ready at http://127.0.0.1:${handle.port}/?token=${token}\n` +
      `[sparkflow web] press Ctrl-C to quit\n\n`,
  );

  let exiting = false;
  async function shutdown(): Promise<void> {
    if (exiting) return;
    exiting = true;
    await handle.close();
    process.exit(0);
  }

  process.on("SIGINT", () => void shutdown());
  process.on("SIGTERM", () => void shutdown());
  process.on("SIGHUP", () => void shutdown());
}

// Only run main() when this file is the direct entry point, not when imported.
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  main().catch((err) => {
    console.error("[sparkflow frontend] fatal:", err);
    process.exit(1);
  });
}
