#!/usr/bin/env node

/**
 * Frontend daemon — the shared HTTP/SSE/WS server for multi-repo sparkflow.
 *
 * This process is spawned (detached) by the first `sparkflow --web` invocation
 * in any repo. Subsequent invocations find it via ~/.sparkflow/dashboard.json
 * and attach their engine daemons to it via the IPC socket.
 *
 * The process can also be started directly for testing by importing
 * `createFrontendDaemon` and calling it with custom options.
 *
 * Invocation (via web/index.ts --frontend-only):
 *   node frontend-daemon.js <ipc-socket-path> <port>
 *
 * Environment:
 *   SPARKFLOW_WEB_TOKEN — auth token (generated by the caller, 64 hex chars)
 */

import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { createConnection, type Socket } from "node:net";
import { existsSync, readFileSync, statSync, unlinkSync } from "node:fs";
import { extname, resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { WebSocketServer, type WebSocket } from "ws";
import { FrontendIpcServer, type EngineConnection } from "./frontend-ipc-server.js";
import { appendRing, RING_BUFFER_BYTES } from "./ring-buffer.js";
import type { ToolKind } from "./ipc-protocol.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
// frontend-daemon.js lives at <pkg>/dist/src/dashboard/. Package root is 3 up.
const PKG_ROOT = resolve(__dirname, "..", "..", "..");
const STATIC_DIR = resolve(__dirname, "..", "web", "static");
const SRC_STATIC_DIR = resolve(PKG_ROOT, "src", "web", "static");
const NODE_MODULES = resolve(PKG_ROOT, "node_modules");

// ---------------------------------------------------------------------------
// Helpers (shared with server.ts)
// ---------------------------------------------------------------------------

function getCookie(req: IncomingMessage, name: string): string | undefined {
  const header = req.headers.cookie;
  if (!header) return undefined;
  for (const part of header.split(";")) {
    const [k, ...rest] = part.trim().split("=");
    if (k === name) return rest.join("=");
  }
  return undefined;
}

function getQueryToken(url: string): string | undefined {
  const idx = url.indexOf("?");
  if (idx === -1) return undefined;
  const params = new URLSearchParams(url.slice(idx + 1));
  return params.get("token") ?? undefined;
}

function authorized(req: IncomingMessage, token: string): boolean {
  if (getCookie(req, "sf_token") === token) return true;
  if (getQueryToken(req.url ?? "") === token) return true;
  return false;
}

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".map": "application/json; charset=utf-8",
};

function sendJson(res: ServerResponse, status: number, body: unknown): void {
  const payload = Buffer.from(JSON.stringify(body), "utf-8");
  res.writeHead(status, {
    "content-type": "application/json; charset=utf-8",
    "content-length": payload.byteLength,
    "cache-control": "no-store",
  });
  res.end(payload);
}

function serveFile(res: ServerResponse, absPath: string): void {
  try {
    const stat = statSync(absPath);
    if (!stat.isFile()) {
      res.writeHead(404, { "content-type": "text/plain" });
      res.end("not found");
      return;
    }
    const body = readFileSync(absPath);
    const mime = MIME[extname(absPath).toLowerCase()] ?? "application/octet-stream";
    res.writeHead(200, {
      "content-type": mime,
      "content-length": body.byteLength,
      "cache-control": "no-cache",
    });
    res.end(body);
  } catch {
    res.writeHead(404, { "content-type": "text/plain" });
    res.end("not found");
  }
}

const APP_FILES = new Set(["index.html", "client.js", "style.css"]);
const VENDOR_FILES: Record<string, string> = {
  "xterm.css": join(NODE_MODULES, "@xterm", "xterm", "css", "xterm.css"),
  "xterm.mjs": join(NODE_MODULES, "@xterm", "xterm", "lib", "xterm.mjs"),
  "addon-fit.mjs": join(NODE_MODULES, "@xterm", "addon-fit", "lib", "addon-fit.mjs"),
};

function resolveStatic(name: string): string | null {
  const safe = name.replace(/^\/+/, "").replace(/\.\./g, "");
  if (APP_FILES.has(safe)) {
    const srcPath = join(SRC_STATIC_DIR, safe);
    if (existsSync(srcPath)) return srcPath;
    return join(STATIC_DIR, safe);
  }
  return VENDOR_FILES[safe] ?? null;
}

function readJsonBody(req: IncomingMessage): Promise<unknown> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    let bytes = 0;
    req.on("data", (chunk: Buffer) => {
      bytes += chunk.byteLength;
      if (bytes > 64 * 1024) {
        reject(new Error("request body too large"));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (chunks.length === 0) { resolve({}); return; }
      try { resolve(JSON.parse(Buffer.concat(chunks).toString("utf-8"))); }
      catch (err) { reject(err instanceof Error ? err : new Error(String(err))); }
    });
    req.on("error", (err) => reject(err));
  });
}

// ---------------------------------------------------------------------------
// PTY bridge proxy (connects to the primary engine's PTY bridge socket)
// ---------------------------------------------------------------------------

interface PtyBridge {
  onData(cb: (chunk: Buffer) => void): void;
  onChatTool(cb: (tool: ToolKind) => void): void;
  write(bytes: Buffer): void;
  resize(cols: number, rows: number): void;
  setChatTool(tool: ToolKind): void;
  close(): void;
}

function connectPtyBridge(socketPath: string): Promise<PtyBridge> {
  return new Promise((resolve, reject) => {
    const sock: Socket = createConnection(socketPath);
    const dataCbs: Array<(b: Buffer) => void> = [];
    const toolCbs: Array<(t: ToolKind) => void> = [];
    const pendingData: Buffer[] = [];
    let pendingTool: ToolKind | null = null;
    let buf = "";

    const bridge: PtyBridge = {
      onData: (cb) => {
        dataCbs.push(cb);
        if (pendingData.length > 0) {
          const queued = pendingData.splice(0, pendingData.length);
          for (const b of queued) cb(b);
        }
      },
      onChatTool: (cb) => {
        toolCbs.push(cb);
        if (pendingTool) cb(pendingTool);
      },
      write: (bytes) => {
        sock.write(JSON.stringify({ type: "pty_write", bytes: bytes.toString("base64") }) + "\n");
      },
      resize: (cols, rows) => {
        sock.write(JSON.stringify({ type: "pty_resize", cols, rows }) + "\n");
      },
      setChatTool: (tool) => {
        sock.write(JSON.stringify({ type: "set_chat_tool", tool }) + "\n");
      },
      close: () => {
        try { sock.destroy(); } catch { /* ignore */ }
      },
    };

    sock.setEncoding("utf-8");
    sock.on("connect", () => resolve(bridge));
    sock.on("error", (err) => reject(err));
    sock.on("close", () => { /* bridge gone */ });
    sock.on("data", (chunk) => {
      buf += chunk as unknown as string;
      let nl: number;
      while ((nl = buf.indexOf("\n")) !== -1) {
        const line = buf.slice(0, nl);
        buf = buf.slice(nl + 1);
        if (!line) continue;
        try {
          const msg = JSON.parse(line) as { type?: string; bytes?: string; tool?: string };
          if ((msg.type === "snapshot" || msg.type === "pty_data") && typeof msg.bytes === "string") {
            const b = Buffer.from(msg.bytes, "base64");
            if (dataCbs.length === 0) pendingData.push(b);
            else for (const cb of dataCbs) cb(b);
          } else if (msg.type === "chat_tool" && (msg.tool === "claude" || msg.tool === "gemini")) {
            const t = msg.tool;
            if (toolCbs.length === 0) pendingTool = t;
            else for (const cb of toolCbs) cb(t);
          }
        } catch { /* ignore */ }
      }
    });
  });
}

// ---------------------------------------------------------------------------
// Main HTTP server factory (exported for testing)
// ---------------------------------------------------------------------------

export interface FrontendDaemonOptions {
  ipcSocketPath: string;
  port: number;
  token: string;
}

export interface FrontendDaemonHandle {
  port: number;
  ipcSocketPath: string;
  registry: FrontendIpcServer;
  close(): Promise<void>;
}

export async function createFrontendDaemon(opts: FrontendDaemonOptions): Promise<FrontendDaemonHandle> {
  const { ipcSocketPath, token } = opts;

  // Start the IPC server (engine registry)
  const registry = new FrontendIpcServer(ipcSocketPath);
  await registry.listen();

  // Per-repo PTY bridge state. Each attached engine that exposes a bridge
  // gets its own entry: separate connection, separate ring, separate WS
  // fan-out. Lets the UI present a fully-independent chat per repo.
  interface RepoBridge {
    bridge: PtyBridge;
    ring: Buffer;
  }
  const bridges = new Map<string, RepoBridge>();
  // WebSocket clients, grouped by the repoId they're bound to. A client binds
  // to a repo on connect (via ?repoId=...); it stays bound for its lifetime.
  const wsToRepo = new WeakMap<WebSocket, string>();
  const wssRef: { wss: WebSocketServer | null } = { wss: null };

  function broadcastToRepo(repoId: string, payload: string): void {
    if (!wssRef.wss) return;
    for (const ws of wssRef.wss.clients) {
      if (ws.readyState !== ws.OPEN) continue;
      if (wsToRepo.get(ws) !== repoId) continue;
      ws.send(payload);
    }
  }

  function onEngineAttached(conn: EngineConnection): void {
    if (!conn.ptyBridgePath || bridges.has(conn.repoId)) return;
    connectPtyBridge(conn.ptyBridgePath).then((bridge) => {
      const entry: RepoBridge = { bridge, ring: Buffer.alloc(0) };
      bridges.set(conn.repoId, entry);

      bridge.onData((chunk) => {
        entry.ring = appendRing(entry.ring, chunk, RING_BUFFER_BYTES);
        const payload = JSON.stringify({ type: "data", bytes: chunk.toString("base64") });
        broadcastToRepo(conn.repoId, payload);
      });
      bridge.onChatTool((tool) => {
        registry.updateChatTool(conn.repoId, tool);
        // On tool switch the engine clears its ring; do the same here so
        // reconnecting clients don't replay stale bytes from the old session.
        entry.ring = Buffer.alloc(0);
        broadcastToRepo(conn.repoId, JSON.stringify({ type: "chat_tool", tool }));
      });
    }).catch(() => { /* PTY bridge unavailable — engine without chat */ });
  }

  registry.on("engineAttached", onEngineAttached);
  registry.on("engineDetached", (repoId: string) => {
    const entry = bridges.get(repoId);
    if (!entry) return;
    try { entry.bridge.close(); } catch { /* ignore */ }
    bridges.delete(repoId);
  });

  // HTTP server
  const server = createServer((req, res) => {
    const url = req.url ?? "/";
    const pathname = url.split("?")[0];

    const cookieOk = getCookie(req, "sf_token") === token;
    const queryOk = getQueryToken(url) === token;
    if (!cookieOk && !queryOk) {
      res.writeHead(401, { "content-type": "text/plain" });
      res.end("unauthorized");
      return;
    }
    if (!cookieOk && queryOk && pathname === "/") {
      res.writeHead(302, {
        "set-cookie": `sf_token=${token}; Path=/; HttpOnly; SameSite=Strict`,
        location: "/",
      });
      res.end();
      return;
    }

    // Static files
    if (pathname === "/" || pathname === "/index.html") {
      const file = resolveStatic("index.html");
      if (file) return serveFile(res, file);
    }
    if (pathname.startsWith("/static/")) {
      const file = resolveStatic(pathname.slice("/static/".length));
      if (file) return serveFile(res, file);
      res.writeHead(404, { "content-type": "text/plain" });
      res.end("not found");
      return;
    }

    // SSE: fan out all engines' jobs
    if (pathname === "/events") {
      res.writeHead(200, {
        "content-type": "text/event-stream",
        "cache-control": "no-cache",
        connection: "keep-alive",
      });
      const send = () => {
        try {
          const jobs = registry.getAllJobs();
          const repos = registry.getRepos();
          res.write(`data: ${JSON.stringify({ jobs, repos })}\n\n`);
        } catch { /* client gone */ }
      };
      send();
      const unsubscribe = registry.onUpdate(send);
      const heartbeat = setInterval(() => {
        try { res.write(": ping\n\n"); } catch { /* ignore */ }
      }, 15_000);
      req.on("close", () => {
        clearInterval(heartbeat);
        unsubscribe();
      });
      return;
    }

    // GET /repos — list attached repos
    if (pathname === "/repos" && req.method === "GET") {
      return sendJson(res, 200, { repos: registry.getRepos() });
    }

    // Per-repo job routes: /repos/:repoId/jobs/:jobId/action
    const repoJobMatch = pathname.match(
      /^\/repos\/([A-Za-z0-9_-]+)\/jobs\/([A-Za-z0-9_-]+)\/([a-z]+)$/,
    );
    if (repoJobMatch) {
      const [, repoId, jobId, action] = repoJobMatch;
      const engine = registry.getEngine(repoId);

      if (!engine) {
        return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });
      }

      if (action === "log" && req.method === "GET") {
        const params = new URLSearchParams(url.includes("?") ? url.slice(url.indexOf("?") + 1) : "");
        const since = parseInt(params.get("since") ?? "0", 10);
        registry
          .sendCommand(repoId, { type: "getJobDetail", jobId, id: randomBytes(8).toString("hex") })
          .then((r) => {
            if (!r || "error" in r) return sendJson(res, 404, { error: `Job not found: ${jobId}` });
            const output = (r.output as string[]) ?? [];
            const length = output.length;
            const safeFrom = Number.isFinite(since) && since >= 0 && since <= length ? since : 0;
            const lines = output.slice(safeFrom);
            const info = r.info as { state?: string } | undefined;
            sendJson(res, 200, { lines, length, state: info?.state ?? "unknown" });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }

      if (action === "kill" && req.method === "POST") {
        registry
          .sendCommand(repoId, { type: "killJob", jobId, id: randomBytes(8).toString("hex") })
          .then((r) => {
            if (!r || "error" in r) return sendJson(res, 400, { error: (r as { error?: string } | null)?.error ?? "kill failed" });
            sendJson(res, 200, { ok: true });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }

      if (action === "restart" && req.method === "POST") {
        // restart is handled on the engine via IPC
        registry
          .sendCommand(repoId, { type: "killJob", jobId, id: randomBytes(8).toString("hex") })
          .then(() => sendJson(res, 200, { ok: true, message: "job killed; re-dispatch to restart" }))
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }

      if (action === "remove" && req.method === "POST") {
        registry
          .sendCommand(repoId, { type: "removeJob", jobId, id: randomBytes(8).toString("hex") })
          .then((r) => {
            if (!r || "error" in r) return sendJson(res, 400, { error: (r as { error?: string } | null)?.error ?? "remove failed" });
            sendJson(res, 200, { ok: true });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }

      if (action === "nudge" && req.method === "POST") {
        readJsonBody(req)
          .then((body) => {
            const { stepId, message } = body as { stepId?: unknown; message?: unknown };
            if (typeof message !== "string" || !message.trim())
              return sendJson(res, 400, { error: "message is required" });
            if (typeof stepId !== "string" || !stepId)
              return sendJson(res, 400, { error: "stepId is required" });
            return sendJson(res, 400, { error: "nudge not supported over multi-repo IPC in v1" });
          })
          .catch(() => sendJson(res, 400, { error: "invalid request body" }));
        return;
      }

      if (action === "recovery" && req.method === "POST") {
        readJsonBody(req)
          .then((body): Promise<Record<string, unknown> | null> | null => {
            const { action: recoveryAction, message } = body as { action?: string; message?: string };
            if (!recoveryAction || !["retry", "skip", "abort"].includes(recoveryAction)) {
              sendJson(res, 400, { error: "invalid action" });
              return null;
            }
            return registry.sendCommand(repoId, {
              type: "answerRecovery",
              id: randomBytes(8).toString("hex"),
              jobId,
              action: recoveryAction as "retry" | "skip" | "abort",
              message,
            });
          })
          .then((r) => {
            if (!r) return;
            if (typeof r === "object" && "error" in r) sendJson(res, 400, { error: (r as { error?: string }).error });
            else sendJson(res, 200, { ok: true });
          })
          .catch(() => sendJson(res, 500, { error: "engine request failed" }));
        return;
      }
    }

    // Switch the jobs tool for a specific repo's engine.
    const jobToolMatch = pathname.match(/^\/repos\/([A-Za-z0-9_-]+)\/job-tool$/);
    if (jobToolMatch && req.method === "POST") {
      const [, repoId] = jobToolMatch;
      const engine = registry.getEngine(repoId);
      if (!engine) return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });

      readJsonBody(req)
        .then((body): Promise<Record<string, unknown> | null> | null => {
          const { tool } = body as { tool?: string };
          if (tool !== "claude" && tool !== "gemini") {
            sendJson(res, 400, { error: "tool must be 'claude' or 'gemini'" });
            return null;
          }
          return registry.sendCommand(repoId, {
            type: "setJobTool",
            id: randomBytes(8).toString("hex"),
            tool,
          });
        })
        .then((r) => {
          if (!r) return;
          if (typeof r === "object" && "error" in r) {
            sendJson(res, 400, { error: (r as { error?: string }).error });
          } else {
            const tool = (r as { jobTool?: string }).jobTool;
            if (tool === "claude" || tool === "gemini") {
              registry.updateJobTool(repoId, tool);
            }
            sendJson(res, 200, { ok: true });
          }
        })
        .catch(() => sendJson(res, 500, { error: "engine request failed" }));
      return;
    }

    // Workflow start for a specific repo
    const startWorkflowMatch = pathname.match(/^\/repos\/([A-Za-z0-9_-]+)\/start$/);
    if (startWorkflowMatch && req.method === "POST") {
      const [, repoId] = startWorkflowMatch;
      const engine = registry.getEngine(repoId);
      if (!engine) return sendJson(res, 404, { error: `No engine attached for repo: ${repoId}` });

      readJsonBody(req)
        .then((body): Promise<Record<string, unknown> | null> | null => {
          const { workflowPath, cwd, plan, planText, slug, description } =
            body as {
              workflowPath?: string;
              cwd?: string;
              plan?: string;
              planText?: string;
              slug?: string;
              description?: string;
            };
          if (!workflowPath) {
            sendJson(res, 400, { error: "workflowPath is required" });
            return null;
          }
          return registry.sendCommand(repoId, {
            type: "startWorkflow",
            id: randomBytes(8).toString("hex"),
            workflowPath,
            cwd,
            plan,
            planText,
            slug,
            description,
          });
        })
        .then((r) => {
          if (!r) return;
          if (typeof r === "object" && "error" in r) sendJson(res, 400, { error: (r as { error?: string }).error });
          else sendJson(res, 200, r);
        })
        .catch(() => sendJson(res, 500, { error: "engine request failed" }));
      return;
    }

    res.writeHead(404, { "content-type": "text/plain" });
    res.end("not found");
  });

  const wss = new WebSocketServer({ noServer: true });
  wssRef.wss = wss;

  function pickRepoIdFromUrl(url: string): string | null {
    const idx = url.indexOf("?");
    if (idx === -1) return null;
    const params = new URLSearchParams(url.slice(idx + 1));
    const requested = params.get("repoId");
    if (requested && bridges.has(requested)) return requested;
    // Fall back to the first attached engine with a bridge — lets old clients
    // (and the sole-repo default) keep working without an explicit repoId.
    for (const rid of bridges.keys()) return rid;
    return null;
  }

  server.on("upgrade", (req, socket, head) => {
    if ((req.url ?? "").split("?")[0] !== "/chat" || !authorized(req, token)) {
      (socket as Socket).write("HTTP/1.1 401 Unauthorized\r\n\r\n");
      (socket as Socket).destroy();
      return;
    }
    const repoId = pickRepoIdFromUrl(req.url ?? "");
    if (!repoId) {
      (socket as Socket).write("HTTP/1.1 503 Service Unavailable\r\n\r\n");
      (socket as Socket).destroy();
      return;
    }
    wss.handleUpgrade(req, socket as Socket, head, (ws) => {
      wsToRepo.set(ws, repoId);
      wss.emit("connection", ws, req);
    });
  });

  wss.on("connection", (ws: WebSocket) => {
    const repoId = wsToRepo.get(ws);
    if (!repoId) {
      try { ws.close(1011, "no repo"); } catch { /* ignore */ }
      return;
    }
    const entry = bridges.get(repoId);
    if (entry && entry.ring.length > 0) {
      ws.send(JSON.stringify({ type: "data", bytes: entry.ring.toString("base64") }));
    }
    // Announce current chatTool on connect so the UI can initialise its select.
    const tool = registry.getEngine(repoId)?.chatTool;
    if (tool) ws.send(JSON.stringify({ type: "chat_tool", tool }));

    ws.on("message", (raw) => {
      let parsed: unknown;
      try { parsed = JSON.parse(raw.toString("utf-8")); } catch { return; }
      const msg = parsed as { type?: string; bytes?: string; cols?: number; rows?: number; tool?: string };
      const current = bridges.get(repoId);
      if (!current) return;
      if (msg.type === "data" && typeof msg.bytes === "string") {
        try { current.bridge.write(Buffer.from(msg.bytes, "base64")); } catch { /* ignore */ }
      } else if (msg.type === "resize" && Number.isFinite(msg.cols) && Number.isFinite(msg.rows)) {
        try { current.bridge.resize(Math.max(1, msg.cols!), Math.max(1, msg.rows!)); } catch { /* ignore */ }
      } else if (msg.type === "set_chat_tool" && (msg.tool === "claude" || msg.tool === "gemini")) {
        try { current.bridge.setChatTool(msg.tool); } catch { /* ignore */ }
      }
    });
  });

  await new Promise<void>((resolve) => server.listen(opts.port, "127.0.0.1", () => resolve()));

  const address = server.address();
  const boundPort = typeof address === "object" && address ? address.port : opts.port;

  return {
    port: boundPort,
    ipcSocketPath,
    registry,
    close: async () => {
      await registry.close();
      await new Promise<void>((resolve) => server.close(() => resolve()));
    },
  };
}

// ---------------------------------------------------------------------------
// Process entry point
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  if (argv.length < 2) {
    console.error("Usage: frontend-daemon <ipc-socket-path> <port>");
    process.exit(1);
  }
  const [ipcSocketPath, portStr] = argv;
  const port = parseInt(portStr, 10);
  if (Number.isNaN(port) || port < 0) {
    console.error(`Invalid port: ${portStr}`);
    process.exit(1);
  }

  const token = process.env.SPARKFLOW_WEB_TOKEN;
  if (!token || !/^[0-9a-f]{64}$/.test(token)) {
    console.error("[sparkflow frontend] missing or malformed SPARKFLOW_WEB_TOKEN");
    process.exit(1);
  }

  const handle = await createFrontendDaemon({ ipcSocketPath, port, token });

  process.stderr.write(
    `\n[sparkflow web] ready at http://127.0.0.1:${handle.port}/?token=${token}\n` +
      `[sparkflow web] press Ctrl-C to quit\n\n`,
  );

  let exiting = false;
  async function shutdown(): Promise<void> {
    if (exiting) return;
    exiting = true;
    await handle.close();
    process.exit(0);
  }

  process.on("SIGINT", () => void shutdown());
  process.on("SIGTERM", () => void shutdown());
  process.on("SIGHUP", () => void shutdown());
}

// Only run main() when this file is the direct entry point, not when imported.
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  main().catch((err) => {
    console.error("[sparkflow frontend] fatal:", err);
    process.exit(1);
  });
}
